### ISSUE TITLE
Can't find Python executable?

### ISSUE THREAD

**Issue by Globulopolis** [Daplie/letsencrypt-cli#15]
Why this lib required python to be installed?
```
d:\WWW\htdocs\le>npm install letsencrypt-cli
-
> ursa@0.9.4 install d:\WWW\htdocs\le\node_modules\letsencrypt-cli\node_modules\letsencrypt\node_mod
ules\letiny-core\node_modules\ursa
> node-gyp rebuild


d:\WWW\htdocs\le\node_modules\letsencrypt-cli\node_modules\letsencrypt\node_modules\letiny-core\node
_modules\ursa>if not defined npm_config_node_gyp (node "D:\WWW\nodejs\node_modules\npm\bin\node-gyp-
bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (D:\WWW\nodejs\node_modules\npm\node_modules\node-gyp\lib\configu
re.js:401:14)
gyp ERR! stack     at D:\WWW\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:82:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\\WWW\\nodejs\\node.exe" "D:\\WWW\\nodejs\\node_modules\\npm\\node_modules\\node
-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd d:\WWW\htdocs\le\node_modules\letsencrypt-cli\node_modules\letsencrypt\node_modules\let
iny-core\node_modules\ursa
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN optional dep failed, continuing ursa@0.9.4
letsencrypt-cli@1.0.8 node_modules\letsencrypt-cli
├── homedir@0.6.0
├── localhost.daplie.com-certificates@1.2.0
├── mkdirp@0.5.1 (minimist@0.0.8)
├── cli@0.11.2 (exit@0.1.2, glob@5.0.15)
└── letsencrypt@1.4.4 (safe-replace@1.0.2, pyconf@1.1.2, bluebird@3.4.1, request@2.73.0, letiny-core
@1.0.5)
```
What's wrong?

**Comment by coolaj86** [comment]
node-gyp uses python to build C++ node.js modules.

**Comment by coolaj86** [comment]
However, `ursa` is an optional dependency, so nothing failed and you should be fine to use the tool as-is.

That said, I'm publishing a new version soon with many bugfixes and improvements.

**Comment by Globulopolis** [comment]
@coolaj86 thank you for clarification. Waiting for new version.

**Comment by gpetrov** [comment]
@coolaj86 Still no fix?

**Comment by coolaj86** [comment]
It's been fixed.

**Comment by coolaj86** [comment]
Python is not necessary for this library.

**Comment by CunningDJ** [comment]
@coolaj86 greenlock and greenlock-epxress both won't npm install via your coolaj86.com & npmjs.com instructions with an error saying gyp doesn't support Anaconda py3.6.  Why is Python necessary (despite what you're saying here), and why do I need to install an older version of Python just to make this work?

**Comment by coolaj86** [comment]
Node v10 has breaking binary API changes that break ursa, which requires node-gyp, which uses a python build system (assuming node may not be installed yet).

However:

Ignore the Warning!!
===============

When you actually go to use it you will find that everything actually installed just fine.

ursa is only required for ARM systems and makes key generation on other systems faster in production environments.

**Comment by coolaj86** [comment]
Also, please open an issue on the official repository at https://git.coolaj86.com/coolaj86/greenlock-cli.js

I use gitea because it’s open source, decentralized, can be self-hosted, and supports GitHub login.

**Comment by CunningDJ** [comment]
OK, thanks.  I'll charge on and see if I run into more issues.  Troubleshooting this between flights :)
