### ISSUE TITLE
TypeError: Cannot set property 'raw' of null in get-acme-urls.js:33

### ISSUE THREAD

**Issue by JohannesHoppe** [Daplie/letsencrypt-cli#20]
Node.js v6.3.1, Windows 8.1, letsencrypt-cli@2.1.1, fresh install:

```
node_modules\.bin\letsencrypt.cmd certonly --agree-tos --email example@example.org --standalone --domains example.org --config-dir .

D:\myFolder\node_modules\le-acme-core\lib\get-acme-urls.js:33
          err.raw = data;
                  ^

TypeError: Cannot set property 'raw' of null
    at Request._callback (D:\myFolder\node_modules\le-acme-core\lib\get-acme-urls.js:33:19)
    at Request.self.callback (D:\myFolder\node_modules\request\request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (D:\myFolder\node_modules\request\request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (D:\myFolder\node_modules\request\request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Sorry! :cry:

**Comment by coolaj86** [comment]
The error you brought up was actually in `le-acme-core`, but I'm guessing the reason you experienced it was that you didn't pass the `server` argument or passed an mistyped url (or perhaps copied from a mistyped example).

Either way, `rm -rf node_modules/*le*; npm install` and try again. At the very least you'll get a more accurate error message this time which *should* show the offending server url.

**Comment by coolaj86** [comment]
From there I can better help you fix whatever the "real" problem is.

**Comment by JohannesHoppe** [comment]
Man, you have a big amount of different repositories! ;-)
Now the error message is much more descriptive:

```
node_modules\.bin\letsencrypt.cmd certonly --agree-tos --email example@example.org --standalone --domains example.org --config-dir .

[Error]: letsencrypt-cli
SyntaxError: Unexpected token p in JSON at position 4
    at Object.parse (native)
    at Request._callback (D:\myfolder\node_modules\le-acme-core\lib\get-acme-urls.js:31:23)
    at Request.self.callback (D:\myfolder\node_modules\request\request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (D:\myfolder\node_modules\request\request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (D:\myfolder\node_modules\request\request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

response data:
404 page not found


acmeDiscoveryUrl:https://acme-v01.api.letsencrypt.org/directory)
```

There must be a typo somewhere. if i add `--server https://acme-v01.api.letsencrypt.org/directory` then I'm getting the next error message :sunglasses:

**Comment by coolaj86** [comment]
Should be `--server https://acme-v01.api.letsencrypt.org`

**Comment by coolaj86** [comment]
Opps, I was wrong! You were right.

* 'https://acme-v01.api.letsencrypt.org/directory'
* 'https://acme-staging.api.letsencrypt.org/directory'

**Comment by coolaj86** [comment]
Hmmm... well that `404 page not found` is pretty clear as to why it's breaking for you, but it's not down for me.

My best guess is that the server assigned to your area is down for maintenance. I get emails a few times a week from them saying "xyz will be down for maintenance from xx pm to yy pm on zz day"

Check to see if the url works for you just by clicking on it.

**Comment by coolaj86** [comment]
Uh-oh... `https://acme-v01.api.letsencrypt.org/directory)`

Notice the trailing `)`? Is that a typo that you made? Or is there a rouge ')' somehow being added in the code?

**Comment by coolaj86** [comment]
I just did a quick scan and I'm pretty sure you've got a typo on your end because I see where the argument is being passed in `letsencrypt-cli` to `node-letsencrypt` to `le-acme-core` and it seems to just go along without any intervention (as expected). I'll also be running some tests shortly with the new version of `letsencrypt-express`, so I'll know for sure when I do that.

Sorry for the hundred million messages.

**Comment by coolaj86** [comment]
Also, thanks for all of your bug reports and your patience. The past few days I've been pushing a lot of code and I'm glad you're running windows and had an old version of node and all these other things that happen to be finding bugs that I didn't find on my own :-)

**Comment by JohannesHoppe** [comment]
:-)

Okay, so you README.MD says:
```
Want to use the live server?

remove the --server https://acme-staging.api.letsencrypt.org/directory
or change it to --server https://acme-v01.api.letsencrypt.org/directory
```

I did this: `node_modules\.bin\letsencrypt.cmd certonly --agree-tos --email example@example.org --standalone --domains example.org --config-dir .` (private values changed, of course) 
I get the `)` when I don't add the `-- server` param at all. Somewhere default setting seems to be wrong. I also tried to locate the issue, but had no success.

If I add the server param, then it continues with another error. I post this soon.

**Comment by JohannesHoppe** [comment]
Oops! I forgot to re-enable port forwarding. If I add `--server` then it works! I get my certs! yay! :smile: 

However, the default server gives me the provided error!

**Comment by coolaj86** [comment]
Cool beans!

Is that port-forwarding on your home router?

Think you could help with https://github.com/Daplie/holepunch? There's some low-hanging fruit right now where the array of network interfaces isn't in the right format. Easy console.log / forEach / obj[key] type stuff.

https://github.com/Daplie/holepunch/issues/4

https://github.com/Daplie/holepunch/issues/2

**Comment by JohannesHoppe** [comment]
Jep. Home-Router (FRITZ!Box).
What should I do?

**Comment by coolaj86** [comment]
Also: v2.1.2 now requires the `--server` argument (and the default was actually where the typo was, so I just removed it)

**Comment by coolaj86** [comment]
@JohannesHoppe Take a look at the issues, run the code, do some console.log, make a PR for the fix.
