### ISSUE TITLE
Deprecated use of le.challenge. Use le.challenges['http-01'] instead.

### ISSUE THREAD

**Issue by wtchangdm** [Daplie/letsencrypt-cli#21]
Hi, I am using letsencrypt-cli 2.1.2 with node 6.4.0 on Win10 X64 Enterprise.

It worked very well on v1.x, but today I updated node to 6.4 from 6.3.1 and letsencrypt-cli to 2.1.2, and then this happened:

`letsencrypt certonly --domains ***.com --email ***@***.com --webroot --webroot-path C:\nginx\html --agree-tos --config-dir C:\nginx\letsencrypt --server https://acme-v01.api.letsencrypt.org/directory`

```
Deprecated use of le.challenge. Use le.challenges['http-01'] instead.
C:\Users\ltlab\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\letsencrypt\index.js:176
          throw new Error("You must provide opts.approveDomains(domain, certs, callback) to approve certificates");
          ^

Error: You must provide opts.approveDomains(domain, certs, callback) to approve certificates
    at Object.LE.create (C:\Users\ltlab\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\letsencrypt\index.js:176:17)
    at Object.module.exports.run (C:\Users\ltlab\AppData\Roaming\npm\node_modules\letsencrypt-cli\index.js:54:15)
    at C:\Users\ltlab\AppData\Roaming\npm\node_modules\letsencrypt-cli\bin\letsencrypt.js:93:20
    at C:\Users\ltlab\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\mkdirp\index.js:48:26
    at FSReqWrap.oncomplete (fs.js:123:15)
```
I tried to change challenge to http-01 like this:
`letsencrypt certonly --domains ***.com --email ***@***.com -http-01-port=80 --agree-tos --config-dir C:\nginx\letsencrypt --server https://acme-v01.api.letsencrypt.org/directory`

But the same error still occurs. Please let me know if you need further information, thanks!

**Comment by coolaj86** [comment]
Thanks for the report. 
Just published a fix.

**Comment by coolaj86** [comment]
Reinstall and try again and you should be good. :)

**Comment by wtchangdm** [comment]
Yeah it works again, thank you very much!
