### ISSUE TITLE
how does renewal process work?

### ISSUE THREAD

**Issue by dhodgin** [Daplie/letsencrypt-cli#22]
Is there a renewal process implemented for this library? i don't see any documentation about renewing your certs once you have them

this library is great for simply getting a cert but i'm loking to put it into production and can't seem to find an easy way to renew the certs once issued. when i rerun the command it just gives me the same existing cert i already have

i can delete my certs before running the command to reissue new ones but it seems like other libraries have renewal cli options.

are they just not implemented yet or am i missing something?

should i just make a script that removes the existing certs and then runs the issuance command right after then restart the web server?

**Comment by dhodgin** [comment]
there is a renewal folder with config files created in my certs folder too. that's why i figured there must be some way of using that config to renew but i don't see anything in the source supporting it.

**Comment by coolaj86** [comment]
Registration vs renewal is automatic.

The registration function checks for an account and certificate with the associated email address. If it doesn't find it, it registers. If it does find it, it renews.

There's also a `--duplicate` flag to force a renewal.

I believe the default behavior is to renew 10 days before expiry - so if you just run set this in a cron job to run once every day you'll be fine.

**Comment by dhodgin** [comment]
hmm ok well when i use
`--duplicate false` or `--duplicate true` it still gives me a cert issued with the same contents and expiry. perhaps it's not implemented yet to force a renewal?

```
Got certificate(s) for dev.xxxx.ca
        Issued at 2016-09-14T19:16:00.000Z
        Valid until 2016-12-13T19:16:00.000Z
```
i'm worried about putting this on production and letting it go and then the renewal process failing and only having at max 10 days to solve the problem before the certs expire. really would like to test that it can renew if forced so at least then i can set myself a reminder to go in in 81 days and see if the cert got renewed automatically. if not force it and just make the script run every 60 days or so with a force renewal on

**Comment by coolaj86** [comment]
Hmm... I'll have to take a look. I may not be passing `--duplicate` properly. I did test the core library by setting the `renewAt` to happen 90 days early before I published and it worked as expected. This is just a thin wrapper around that, but I do understand your concern.

If you care to look in the index.js here and the docs for `node-letsencrypt` you should be able to see how to coerce the `--duplicate` option to set the `renewAt` in the past and get the result.

I don't have the time to check on it right now, but I am confident that the core is well tested in various situations (I refactored/rewrote it last month to fix the problem of renewal and made sure to test it thoroughly for my own needs).

**Comment by RamIdeas** [comment]
I am experiencing this too:

```
Got certificate(s) for ...
        Issued at ...
        Valid until ...
```

`--duplicate` wasn't forcing a renewal either

But renaming `~/letsencrypt/etc/live/abc.xyz` to `~/letsencrypt/etc/live/_abc.xyz` did force it and I ran into an issue similar to https://github.com/Daplie/letsencrypt-express/issues/74

<details>
  <summary>In fact, I'm getting the exact same object-literal logged to the console (amongst the stack dump)</summary>
```
TODO: modules which depend on this module should expose this error properly but since some of them don't, I expose it here directly:
Error: [Error] letiny-core: not 200 ok
    at bodyToError (/usr/lib/node_modules/letsencrypt-cli/node_modules/le-acme-core/lib/get-certificate.js:55:15)
    at /usr/lib/node_modules/letsencrypt-cli/node_modules/le-acme-core/lib/get-certificate.js:99:20
    at Request._callback (/usr/lib/node_modules/letsencrypt-cli/node_modules/le-acme-core/lib/acme-client.js:113:7)
    at Request.self.callback (/usr/lib/node_modules/letsencrypt-cli/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/lib/node_modules/letsencrypt-cli/node_modules/request/request.js:1048:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/letsencrypt-cli/node_modules/request/request.js:969:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
{ type: 'urn:acme:error:malformed',
  detail: 'Parse error reading JWS',
  status: 400 }
[Error]: letsencrypt-cli
```
</details>

Using:
node: v6.7.0
npm: 3.10.8
OS: Raspbian GNU/Linux 8 (jessie)

**Comment by insightfuls** [comment]
I've been looking at this project recently and can confirm:
- Renewals happen within 7 days by default, and it currently isn't configurable
- `--duplicate` is indeed not currently being passed correctly

I've provided a pull request exposing --renew-within, fixing --duplicate, and organising the options a little better. I'm afraid it applies on top of some other work I've done, and I'm sure won't rebase cleanly onto master directly, but only the final commit showing up in the pull request is actually about this.

https://github.com/Daplie/letsencrypt-cli/pull/25

**Comment by insightfuls** [comment]
Correction: `--duplicate` was passed correctly, but it didn't work because certificates were being renewed in the background, but the existing certificates were returned 'in the foreground' and the program explicitly exited. The pull request has been updated to fix this.

**Comment by insightfuls** [comment]
Fix now merged and released.
