### ISSUE TITLE
Clarify if server argument is optional or required

### ISSUE THREAD

**Issue by gitgrimbo** [Daplie/letsencrypt-cli#29]
Hi,

If I try and run `letsencrypt` without the `--server` argument I get the following error:

```
    throw new Error("You must specify a server to use with --server");
    ^

Error: You must specify a server to use with --server
    at Object.module.exports.run (C:\Users\grimbo\AppData\Roaming\npm\node_modules\letsencrypt-cli\index.js:70:11)
    at C:\Users\grimbo\AppData\Roaming\npm\node_modules\letsencrypt-cli\bin\letsencrypt.js:106:20
    at C:\Users\grimbo\AppData\Roaming\npm\node_modules\letsencrypt-cli\node_modules\mkdirp\index.js:48:26
    at FSReqWrap.oncomplete (fs.js:123:15)
```

The following parts of [`README.md`](https://github.com/Daplie/letsencrypt-cli/blob/5a1abb7e83ab8c16c6ca3a999ecea3b94ccda536/README.md) seem to suggest `--server` is optional.

1) Usage:

*remove the --server https://acme-staging.api.letsencrypt.org/directory*

2) Command line options

*--server [STRING]         ACME Directory Resource URI. (Default is https://acme-v01.api.letsencrypt.org/directory))*

**Comment by coolaj86** [comment]
Yes, I need to fix the readme. Thanks.
