### ISSUE TITLE
standalone certificate generation failed on AWS-with nvm

### ISSUE THREAD

**Issue by vmahadev** [Daplie/letsencrypt-cli#30]
ubuntu@ip-172-31-53-179:~/apps/bots/ListBot$ npm install -g letsencrypt-cli@2.x
/home/ubuntu/.nvm/versions/node/v6.9.1/bin/letsencrypt -> /home/ubuntu/.nvm/versions/node/v6.9.1/lib/node_modules/letsencrypt-cli/bin/letsencrypt.js
/home/ubuntu/.nvm/versions/node/v6.9.1/bin/letsencrypt-node -> /home/ubuntu/.nvm/versions/node/v6.9.1/lib/node_modules/letsencrypt-cli/bin/letsencrypt.js

> ursa@0.9.4 install /home/ubuntu/.nvm/versions/node/v6.9.1/lib/node_modules/letsencrypt-cli/node_modules/ursa
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/home/ubuntu/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/which/which.js:14:12)
gyp ERR! stack     at F (/home/ubuntu/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/which/which.js:69:19)
gyp ERR! stack     at E (/home/ubuntu/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/which/which.js:81:29)
gyp ERR! stack     at /home/ubuntu/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/which/which.js:90:16
gyp ERR! stack     at /home/ubuntu/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /home/ubuntu/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Linux 3.13.0-91-generic
gyp ERR! command "/home/ubuntu/.nvm/versions/node/v6.9.1/bin/node" "/home/ubuntu/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/.nvm/versions/node/v6.9.1/lib/node_modules/letsencrypt-cli/node_modules/ursa
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
/home/ubuntu/.nvm/versions/node/v6.9.1/lib

le.challenges[http-01].loopback should be defined as function (opts, domain, token, keyAuthorization, cb) { ... } and should prove (by external means) that the ACME server challenge 'http-01' will succeed
le.challenges[tls-sni-01].loopback should be defined as function (opts, domain, token, keyAuthorization, cb) { ... } and should prove (by external means) that the ACME server challenge 'tls-sni-01' will succeed
/home/ubuntu/.nvm/versions/node/v6.9.1/lib/node_modules/letsencrypt-cli/lib/servers.js:53
          throw err;
          ^

Error: listen EACCES 0.0.0.0:80
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1244:19)
    at listen (net.js:1293:10)
    at Server.listen (net.js:1389:5)
    at /home/ubuntu/.nvm/versions/node/v6.9.1/lib/node_modules/letsencrypt-cli/lib/servers.js:41:16
    at Array.forEach (native)
    at Object.startServers (/home/ubuntu/.nvm/versions/node/v6.9.1/lib/node_modules/letsencrypt-cli/lib/servers.js:37:18)
    at Object.module.exports.run (/home/ubuntu/.nvm/versions/node/v6.9.1/lib/node_modules/letsencrypt-cli/index.js:93:25)
    at /home/ubuntu/.nvm/versions/node/v6.9.1/lib/node_modules/letsencrypt-cli/bin/letsencrypt.js:106:20
    at /home/ubuntu/.nvm/versions/node/v6.9.1/lib/node_modules/letsencrypt-cli/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:123:15)

**Comment by vmahadev** [comment]
Installation failed 👎

**Comment by coolaj86** [comment]
`Error: listen EACCES 0.0.0.0:80`: you didn't run it with the correct permissions.

You run with `sudo` or allow node to use privileged ports:

```
sudo setcap 'cap_net_bind_service=+ep' $(which node)
```

**Comment by Andre221** [comment]
DON'T WORK

**Comment by coolaj86** [comment]
@Andre221 the official repository is https://git.coolaj86.com/coolaj86/greenlock-cli.js

Also, have you read the others' comments? If you're still having trouble open an issue at https://git.coolaj86.com/coolaj86/greenlock-cli.js and I can help you debug.
