### ISSUE TITLE
loopback should be defined as function

### ISSUE THREAD

**Issue by ear7h** [Daplie/letsencrypt-cli#31]
I am trying to get a certificate for my nodejs server and when I put in the follwing command:

`letsencrypt certonly --agree-tos --email xx@x.com --standalone --domains ear7h.net,www.ear7h.net --server https://acme-staging.api.letsencrypt.org/directory --config-dir ~/letsencrypt/etc`

it gives me the error:

`le.challenges[http-01].loopback should be defined as function (opts, domain, token, keyAuthorization, cb) { ... } and should prove (by external means) that the ACME server challenge 'http-01' will succeed
le.challenges[tls-sni-01].loopback should be defined as function (opts, domain, token, keyAuthorization, cb) { ... } and should prove (by external means) that the ACME server challenge 'tls-sni-01' will succeed
/usr/local/lib/node_modules/letsencrypt-cli/lib/servers.js:53
          throw err;`

I am using the https method for creating servers and its running on port 80. I have tried both with the server running and not running. Perhaps the problem is with my server as various other methods of setting up ssl have given me issues. Any advice would be greatly apreciated, that you in advance.

**Comment by coolaj86** [comment]
Fixed in Official Repository
=========

This functionality was moved to https://git.coolaj86.com/coolaj86/acme-v2.js, which trickles into the updated project at https://git.coolaj86.com/coolaj86/greenlock-cli.js
