### ISSUE TITLE
Correct syntax to the simplest --expand command

### ISSUE THREAD

**Issue by ppKrauss** [Daplie/letsencrypt-cli#32]
Hi, can I submit question here?  It is also a suggestion to enhance documentation.

 **How to use `--expand`, what the correct syntax?** 

-----

Supposing that *domain1* is the main domain, and *domain2* and *domain3* was created with the initial command, <br/>`letsencrypt --apache -d domanin1 -d www.domanin1 -d wiki.domanin1 -d domanin2 -d www.domanin2 -d domanin3`

... What the correct syntax to add a *domain4*? 1, 2 ... or 5?

 1. `letsencrypt --apache --expand domanin4`
 2. `letsencrypt --apache --expand -d domanin4`
 3. `letsencrypt --expand -d domanin4`
 4. `letsencrypt --apache --expand -d domanin1 -d domanin4`
 5. `letsencrypt --apache --expand -d domanin1 -d www.domanin1 -d wiki.domanin1 -d domanin2 -d www.domanin2 -d domanin3 -d domain4`

PS: need to repeat all domains and subdomains in the expansion?

**Comment by insightfuls** [comment]
`--expand` is a certbot option that we haven't implemented/don't support. Likewise, we don't support `--apache` (though we had an `--apache` option in an older version). However, we have a `--hooks` option which has similar functionality. Use the `--help` option to see a list of supported options and refer to the README.md file. Pretty much everything is demonstrated and documented there that we support. If it's not there, we probably don't support it.

**Comment by coolaj86** [comment]
tls-sni-01 is now deprecated
=========

For anyone accidentally coming here and finding this, this has been removed from the documentation in the official [Greenlock CLI](https://git.coolaj86.com/coolaj86/greenlock-cli.js) that lives at <https://git.coolaj86.com/coolaj86/greenlock-cli.js> because `tls-sni-01` has been deprecated due to security concerns.
