### ISSUE TITLE
provide CLI w/ account private key to sign requests

### ISSUE THREAD

**Issue by lucendio** [Daplie/letsencrypt-cli#4]
HI,

I thinks its more like a question/feature request, because I am not able to locate the part(s) in the code base which might handle this. however I managed to fine it a dependency [node-letsencrypt](https://github.com/Daplie/node-letsencrypt/blob/1c7264538c8fea2616e4b4c28e79006ad212e331/lib/core.js#L258)
So what does the CLI thinks where the account private key is located? And would it be possible to provide the CLI with the location (or content) of the acoounts private key?

thanks for any advice

**Comment by coolaj86** [comment]
Yes, totally possible. At CES for the week. Ping me on Monday and I'll get that set up, shouldn't be a big deal to add.

**Comment by coolaj86** [comment]
Do you still need this?

Same as https://github.com/Daplie/letsencrypt-express/issues/18

**Comment by lucendio** [comment]
yes, please. that would be great.

**Comment by coolaj86** [comment]
This is fixed in v2.0.0, which was just published.
https://github.com/Daplie/letsencrypt-cli

Use `--accountKeyPath /path/to/privkey.pem`
