### ISSUE TITLE
Not Implemented message when specifying --config

### ISSUE THREAD

**Issue by jonnor** [Daplie/letsencrypt-cli#6]
`[LE /lib/core.js] retrieve from domainKeyPath NOT IMPLEMENTED (please file an issue to remind me about this)`

When not specifying --config, this message does not appear.

**Comment by coolaj86** [comment]
Same as https://github.com/Daplie/letsencrypt-express/issues/18

**Comment by coolaj86** [comment]
This is fixed in v2.0.0, which was just published.
https://github.com/Daplie/letsencrypt-cli
