### ISSUE TITLE
New lines in pem files

### ISSUE THREAD

**Issue by jsumners** [Daplie/letsencrypt-cli#8]
I'm generating certificates that will be used by HAProxy. It expects `cert > privkey > chain`. After using *letsencrypt-cli* to generate the files, I did:

```bash
$ cat cert.pem privkey.pem chain.pem > fullcert.pem
```

This resulted in a bad file because `cert.pem` does not end with a new line. That is, I end up with a line:

```
-----END CERTIFICATE----------BEGIN RSA PRIVATE KEY-----^M
```

Which leads to a second issue (well, more of a quibble). The `privkey.pem` file has CRLF line ending instead of just LF. It'd be nice if the line endings were consistent for all three files.

**Comment by coolaj86** [comment]
Would you like to do a PR to letiny to fix this?
https://github.com/Daplie/letiny-core/issues/11

I'll update node-letsencrypt as part of the v2 push within a day or two.

Closing since this isn't actually a problem with the cli

**Comment by jsumners** [comment]
I'm using https://github.com/hlandau/acme now.
